### ISSUE TITLE
Кнопка "Назад" не работает так как ожидается.

### ISSUE THREAD

**Issue by maks2027** [1C-Connect/1cconnect-text-bot#12]
Добрый день. 
Кнопка back_button возвращает на предыдущее меню, но если в предыдущем меню тоже есть кнопка "назад" то она тоже буквально возвращает назад, то есть в меню в котором до этого были, а не на уровень ниже.

Пример:
Мы в меню на уровне 2 и переходим в меню на уровень 3, жмём кнопку "назад" и возвращаемся на уровень 2, на уровне 2 жмём кнопку "назад " и возвращаемся на уровень 3.

Ожидается что с помощью многократного нажатия "назад" мы в итоге спустимся на уровень 1 в главное меню.

**Comment by ros-tel** [comment]
Добрый день.
Такое поведение и задумывалось.
Можете с равнить как работает кнопка назад в мобильных приложениях.
Возможно, название неочень удачное, но можно в своей конфигурации назвать "на уровень выше".

**Comment by LilKirill00** [comment]
Добрый день. Расписал для Readme как работает back_button, вот блок который может объяснить как решить вашу проблему

### Как вернуться в предыдущее меню

```yaml
buttons:
  - button:
      text: 'Назад'
      back_button: true
```

По нажатию на `back_button` пользователя вернет в предыдущее меню в котором он находился. Более понятно через пример:

|На какую кнопку пользователь нажал|Куда попал|На какое меню теперь ссылается back_button|
|----------|----------|----------|
|Меню|start|start|
|2.1|lvl_2.1|start|
|Назад|start|lvl_2.1|
|2.1|lvl_2.1|start|
|3.1|lvl_3.1|lvl_2.1|
|Назад|lvl_2.1|lvl_3.1|
|Назад|lvl_3.1|lvl_2.1|

```yaml
menus:
  start:
    answer:
      - chat: "Выберите пункт меню"
    buttons: # lvl:1
      - button: 
          text: '2.1'
          menu:
            id: 'lvl_2.1'
            answer:
              - chat: "Вы на уровне 2.1"
            buttons: # lvl:2
              - button:
                  text: "Назад"
                  back_button: true 
              - button:
                  text: '3.1'
                  menu:
                    id: 'lvl_3.1'
                    answer:
                      - chat: "Вы на уровне 3.1"
                    buttons: # lvl:3  
                      - button:
                          text: "Назад"
                          back_button: true 
```

Если есть необходимость реализовать переход с последнего уровня до первого уровня, то необходимо придерживаться простых правил:
- если уровень не последний в цепочке, то используйте `goto`
- если последний, то можете использовать `back_button` вместо `goto`

Пример как реализовать кнопку "Назад" с последнего уровня до start:

```yaml
menus:
  start:
    answer:
      - chat: "Выберите пункт меню"
    buttons: # lvl:1
      - button: 
          text: '2.1'
          menu:
            id: 'lvl_2.1'
            answer:
              - chat: "Вы на уровне 2.1"
            buttons: # lvl:2
              - button:
                  text: "Назад"
                  goto: 'start' # указываем переход на lvl:1
              - button:
                  text: '3.1'
                  menu:
                    id: 'lvl_3.1'
                    answer:
                      - chat: "Вы на уровне 3.1"
                    buttons: # lvl:3  
                      - button:
                          text: "Назад"
                          # на последнем уровне можно использовать back_button либо также как раньше goto на предыдущий уровень
                          back_button: true 
                          # `back_button: true` в данном примере можно заменить на `goto: 'lvl_2.1'`
```
